tangle-network/blueprint

- .envrc
- .gitignore
- flake.lock
- flake.nix
- rust-toolchain.toml
This PR just adds the skeleton for Nix and Flakes for development environment.
> Add Nix and Flakes devenv

- Cargo.toml
- gadget-core/src/gadget/manager.rs
- gadget-core/src/job_manager.rs
- test-gadget/Cargo.toml
- test-gadget/src/gadget.rs
- test-gadget/src/lib.rs
- test-gadget/src/message.rs
- test-gadget/src/work_manager.rs
- test-gadget/tests/basic.rs
- test-gadget/tests/dfft.rs
- test-gadget/tests/dmsm.rs
- test-gadget/tests/zk_network.rs
- webb-gadget/src/gadget/mod.rs
- webb-gadget/src/lib.rs
- zk-gadget/src/lib.rs
> Draft: Refactor tests. Add dfft/dmsm tests inside test-gadget

- Cargo.lock
- Cargo.toml
- gadget-common/Cargo.toml
- gadget-common/src/client.rs
> feat: switch to webb SDK and fix pallet submitter

- .github/workflows/validate_pr.yml
- Cargo.lock
- gadget-common/Cargo.toml
- gadget-common/src/full_protocol.rs
- gadget-common/src/gadget/mod.rs
- gadget-common/src/gadget/network/mod.rs
- gadget-common/src/keystore.rs
- gadget-common/src/lib.rs
- gadget-core/src/job_manager.rs
- protocols/bls/src/lib.rs
- protocols/bls/src/protocol/keygen.rs
- protocols/bls/src/protocol/signing.rs
- protocols/dfns-cggmp21/Cargo.toml
- protocols/dfns-cggmp21/src/lib.rs
- protocols/dfns-cggmp21/src/protocols/key_refresh.rs
- protocols/dfns-cggmp21/src/protocols/key_rotate.rs
- protocols/dfns-cggmp21/src/protocols/keygen.rs
- protocols/dfns-cggmp21/src/protocols/sign.rs
- protocols/dfns-cggmp21/tests/dfns.rs
- protocols/stub/README.md
- protocols/stub/src/lib.rs
- protocols/zk-saas/Cargo.toml
- protocols/zk-saas/src/lib.rs
- protocols/zk-saas/src/network/mod.rs
- protocols/zk-saas/src/protocol/mod.rs
- protocols/zk-saas/tests/zksaas.rs
- test-utils/src/lib.rs
> Message Recording + Port protocols to use the new FullProtocolConfig + test macros + Sqlite backend

- Cargo.lock
- Cargo.toml
- flake.nix
- gadget-common/Cargo.toml
- gadget-common/src/channels.rs
- gadget-common/src/client.rs
- gadget-common/src/full_protocol.rs
- gadget-common/src/gadget/message.rs
- gadget-common/src/gadget/mod.rs
- gadget-common/src/gadget/network/gossip.rs
- gadget-common/src/gadget/network/mod.rs
- gadget-common/src/lib.rs
- protocols/bls/src/protocol/keygen.rs
- protocols/bls/src/protocol/signing.rs
- protocols/dfns-cggmp21/src/protocols/key_refresh.rs
- protocols/dfns-cggmp21/src/protocols/key_rotate.rs
- protocols/dfns-cggmp21/src/protocols/keygen.rs
- protocols/dfns-cggmp21/src/protocols/sign.rs
- protocols/dfns-cggmp21/src/protocols/util.rs
- protocols/dfns-cggmp21/tests/dfns.rs
- protocols/stub/src/lib.rs
- protocols/zk-saas/src/lib.rs
- protocols/zk-saas/src/network/mod.rs
- protocols/zk-saas/src/protocol/mod.rs
- protocols/zk-saas/tests/zksaas.rs
- test-utils/src/lib.rs
- test-utils/src/mock.rs
Needs: https://github.com/webb-tools/webb-rs/pull/184
Related: https://github.com/webb-tools/tangle/pull/489
> Update Gossip Networking

- Cargo.lock
- shell/Cargo.toml
- shell/src/network/gossip.rs
- shell/src/network/handlers/connections.rs
- shell/src/network/handlers/p2p.rs
- shell/src/network/setup.rs
- shell/src/shell.rs
> feat: add handshake logic with verification

- Cargo.lock
- protocols/bls/src/constants.rs
- protocols/bls/src/lib.rs
- protocols/silent-shard-dkls23-ll/src/constants.rs
- protocols/silent-shard-dkls23-ll/src/lib.rs
- protocols/zcash-frost/src/constants.rs
- shell/Cargo.toml
- shell/src/network/gossip.rs
- shell/src/network/handlers/identify.rs
- shell/src/network/setup.rs
- shell/src/shell.rs
Closes #115
Only missing part for this PR is the zksaas service to be added.
> feat: Support more gadgets in the shell

- Cargo.lock
- protocols/dfns-cggmp21/src/protocols/key_rotate.rs
> Use proper scheme in rotation job result submission

- README.md
- scripts/run-gadget-local.sh
- shell-configs/local-testnet-1.toml
- shell-configs/local-testnet-2.toml
> Add script to run gadget and update readme

- Cargo.toml
- executor/Cargo.toml
- executor/src/lib.rs
- executor/src/process/manager.rs
- executor/src/process/mod.rs
- executor/src/process/types.rs
- executor/src/process/utils.rs
> [DRAFT] Gadget Executor

- eigen-gadget/src/avs/mod.rs
- eigen-gadget/src/challenger/mod.rs
- eigen-gadget/src/operator.rs
- eigen-tangle-avs/src/operator.rs
- eigen-utils/src/avs_registry/mod.rs
- eigen-utils/src/avs_registry/writer.rs
- eigen-utils/src/crypto/bls.rs
- eigen-utils/src/crypto/ecdsa.rs
- eigen-utils/src/crypto/mod.rs
- eigen-utils/src/types.rs
- flake.lock
- flake.nix
Fixes build errors in eigen integration branch.
> fix: build errors

- sdk/Cargo.toml
- sdk/src/lib.rs
- sdk/src/logging/mod.rs
- sdk/src/logging/slog.rs
- sdk/src/logging/tracing.rs
- sdk/src/logging/wasm.rs
This PR addresses #156. It includes modules for Tracing-style logging in both Native and WASM contexts.
> Gadget Logging

- Cargo.lock
- blueprint-metadata/Cargo.toml
- blueprint-metadata/src/lib.rs
- flake.lock
Starting to use proper file locks instead of my previous buggy implantation
Read more about [`flock(2)`](https://man7.org/linux/man-pages/man2/flock.2.html)
> Update how we work with blueprint.lock files

- Cargo.lock
- Cargo.toml
- blueprints/incredible-squaring/src/main.rs
- environments/tangle/src/api.rs
- sdk/src/env.rs
- sdk/src/events_watcher/tangle.rs
- sdk/src/keystore/mod.rs
- shell-manager/Cargo.toml
- shell-manager/src/config.rs
- shell-manager/src/gadget/native.rs
- shell-manager/src/main.rs
> feat(gadget-sdk): handle PreRegistration Event

- blueprint-manager/src/executor/event_handler.rs
- blueprints/incredible-squaring/Cargo.toml
- blueprints/incredible-squaring/src/lib.rs
- blueprints/incredible-squaring/src/main.rs
- flake.lock
- macros/blueprint-proc-macro/src/benchmark.rs
- sdk/src/env.rs
- sdk/src/keystore/backend/mem.rs
- sdk/src/keystore/mod.rs
- sdk/src/lib.rs
- sdk/src/network/setup.rs
- sdk/src/run.rs
> feat: add benchmarking mode

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- blueprint-manager/Cargo.toml
- blueprint-test-utils/src/test_ext.rs
- common/Cargo.toml
- common/src/channels.rs
- common/src/debug_logger.rs
- common/src/keystore.rs
- common/src/lib.rs
- common/src/locks.rs
- core/src/gadget/manager.rs
- core/src/job/mod.rs
- gadget-io/Cargo.toml
- sdk/Cargo.toml
- sdk/src/env.rs
- sdk/src/lib.rs
- sdk/src/random.rs
- sdk/src/tx/tangle.rs
* Renamed "Validate PR" to "CI" since it isn't run exclusively on PRs
* Added a `features` job to test that the crates build with each feature (including `--no-default-features`) using `cargo-hack`
* Added a test for WASM builds (commented out for now)
> Add more checks to CI

- Cargo.lock
- sdk/Cargo.toml
- sdk/src/benchmark/mod.rs
- sdk/src/clients/mod.rs
- sdk/src/clients/tangle/runtime.rs
- sdk/src/clients/tangle/services.rs
- sdk/src/config.rs
- sdk/src/events_watcher/evm.rs
- sdk/src/events_watcher/mod.rs
- sdk/src/events_watcher/substrate.rs
- sdk/src/events_watcher/tangle.rs
- sdk/src/keystore/backend/fs.rs
- sdk/src/keystore/backend/mod.rs
- sdk/src/keystore/bls381.rs
- sdk/src/keystore/ecdsa.rs
- sdk/src/keystore/ed25519.rs
- sdk/src/lib.rs
- sdk/src/metrics/mod.rs
- sdk/src/mutex_ext.rs
- sdk/src/network/channels.rs
- sdk/src/network/setup.rs
- sdk/src/prometheus/mod.rs
- sdk/src/prometheus/shared.rs
- sdk/src/prometheus/standard.rs
- sdk/src/random.rs
- sdk/src/run.rs
- sdk/src/slashing/reports.rs
- sdk/src/store/local_database.rs
- sdk/src/store/mod.rs
- sdk/src/tx/tangle.rs
A lot of docs either don't exist or are just a repetition of the item name. This already has a bunch of improvements, but I'm waiting on #252 before this is finished.
> Improve SDK docs

- Cargo.toml
- blueprint-test-utils/src/test_ext.rs
- sdk/Cargo.toml
- sdk/src/lib.rs
> Remove unused workspace dependencies

- Cargo.lock
- README.md
- cli/README.md
Companion PR: https://github.com/webb-tools/blueprint-template/pull/7
> chore(cli): Update READMEs with Download Links

- Cargo.lock
- Cargo.toml
- blueprints/incredible-squaring/Cargo.toml
- sdk/Cargo.toml
- sdk/src/config.rs
- sdk/src/keystore/backend/fs.rs
- sdk/src/keystore/backend/mem.rs
- sdk/src/keystore/bn254.rs
- sdk/src/keystore/mod.rs
Removes Git Dependencies so SDK can be published to Crates.io
> Remove Git Dependencies for Publishing

- macros/context-derive/src/evm.rs
- macros/context-derive/src/subxt.rs
This pull request includes several important changes to improve caching mechanisms.
* [`macros/context-derive/src/evm.rs`](diffhunk://#diff-24e15fd4a94fe2b9f001f2dd05250f58f002e2f39632b5abdd5579a4c1d7ece9L33-R61): Implemented caching for the provider in the `evm_provider` function using `std::sync::OnceLock`. This ensures that the provider is only created once and reused for subsequent calls.
* [`macros/context-derive/src/subxt.rs`](diffhunk://#diff-c96c5913f3279d9b616ce82ca5085318c40e10e66a9e2e8a1ca2369a66260435L26-R43): Implemented caching for the client in the `tangle_client` function using `std::sync::OnceLock`. This ensures that the client is only created once and reused for subsequent calls.
Closes #320
> feat: Cache Subxt OnlineClient and EVM Providers

- blueprint-manager/src/sources/testing.rs
- macros/blueprint-proc-macro/src/job.rs
Hello
I found and fixed several minor spelling issues.
Br, Elias.
> docs fix spelling issues

- Cargo.lock
- Cargo.toml
- rust-toolchain.toml
Also pin to the latest nightly
> chore: bump rustdoc-types

- blueprints/incredible-squaring/src/lib.rs
- blueprints/incredible-squaring/src/main.rs
- macros/blueprint-proc-macro/src/job.rs
> Fix bug with tangle contexts

- blueprints/incredible-squaring/Cargo.toml
- cli/src/deploy.rs
- macros/blueprint-proc-macro-core/src/lib.rs
- macros/playground/Cargo.toml
> fix(cargo-tangle): bake blueprint json

- cli/src/deploy.rs
- sdk/src/tx/tangle.rs
This pull request includes several changes to improve the handling of transaction progress and the testing configuration. The most important changes include updating submodule commits, adding a new trait for transaction progress handling, and modifying the deployment process to differentiate between test and non-test environments.
* Added a new trait `TxProgressExt` in `sdk/src/tx/tangle.rs` for handling transaction progress, including methods `wait_for_in_block` and `wait_for_in_block_success`.
* Implemented the `TxProgressExt` trait for `subxt::tx::TxProgress`.
* Modified `deploy_to_tangle` function in `cli/src/deploy.rs` to conditionally wait for transaction finalization based on the test configuration.
* Added conditional compilation for testing in `cli/src/deploy.rs` to use …
> feat(sdk): add TxProgressExt trait

- Cargo.lock
- Cargo.toml
- blueprint-build-utils/Cargo.toml
- blueprint-build-utils/src/lib.rs
- blueprints/incredible-squaring-eigenlayer/Cargo.toml
- blueprints/incredible-squaring-eigenlayer/build.rs
- blueprints/incredible-squaring-symbiotic/Cargo.toml
- blueprints/incredible-squaring-symbiotic/build.rs
Adds a utility library for build scripts used in blueprints
#432
> feat(blueprint-build-utils): utilities lib for build scripts

- .github/workflows/ci.yml
- sdk/src/ctx.rs
- sdk/src/docker.rs
`nextest` doesn't support doc tests currently. We need to make sure that examples in the docs compile.
**Needs #382 since it fixes another failing doc test**
> fix(ci): add doc tests to CI

- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/src/create.rs
- cli/src/main.rs
> feat(cargo-tangle): force initialize git submodules

- blueprint-serde/src/lib.rs
From https://github.com/tangle-network/gadget/pull/429#discussion_r1828301717
> feat(gadget-blueprint-serde): add crate docs

- blueprints/incredible-squaring-eigenlayer/src/contexts/aggregator.rs
- blueprints/incredible-squaring-eigenlayer/src/tests.rs
Fixes the race condition in the aggregator causing the EigenLayer Incredible Squaring Blueprint to sometimes fail.
Addresses #490
> fix: solve aggregator initialization race condition

- Cargo.lock
- Cargo.toml
- blueprint-manager/src/lib.rs
- blueprint-metadata/src/lib.rs
- blueprint-test-utils/src/tangle/transactions.rs
- blueprint-test-utils/src/test_ext.rs
- blueprints/incredible-squaring/Cargo.toml
- macros/blueprint-proc-macro-core/src/lib.rs
- macros/context-derive/src/services.rs
- sdk/src/contexts/services.rs
- sdk/src/lib.rs
- sdk/src/runners/tangle.rs
This pull request includes several updates and improvements across multiple files to enhance the functionality and maintainability of the codebase. The most significant changes involve updating dependencies, modifying function signatures, and introducing new types for better data handling.
Dependency Updates:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L66-R66): Updated `tangle-subxt` dependency from version `0.5.0` to `0.6.0`.
Function Signature Modifications:
* [`blueprint-test-utils/src/tangle/transactions.rs`](diffhunk://#diff-8d304b7f929bae6e39644cb30821d692531da4dcd5e1d00e1fa0c9c313852deeR53-R58): Added `value` parameter to `register_blueprint` and `request_service` functions to support additional data during service registration …
> chore(gadget-sdk)!: update to latest tangle

- cli/src/deploy.rs
- cli/src/foundry/forge.rs
- cli/src/keys.rs
> feat(cargo-tangle): improve error handling

- Cargo.lock
- Cargo.toml
This pull request address the following issue #538 
Dependency updates:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L66-R66): Updated the `tangle-subxt` dependency from a Git reference to version `0.7.1`.
> chore: update to latest tangle-subxt 0.7.1

- .gitignore
- Cargo.toml
- crates/event-listeners/core/src/lib.rs
- crates/runners/core/src/config.rs
- crates/runners/core/src/runner.rs
- crates/runners/core/src/tests.rs
- crates/testing-utils/core/src/runner.rs
- crates/testing-utils/tangle/src/runner.rs
Goal with this feature is to get rid of the need to run the runner inside of a thread and instead have this handled in the backend.
> feat: testing improvement

- blueprints/examples/src/tests.rs
- blueprints/incredible-squaring-eigenlayer/src/tests.rs
- blueprints/incredible-squaring/src/tests.rs
- crates/testing-utils/tangle/src/runner.rs
Resolves bug causing some pre-registration tests to fail and updates following improvement that allows test runner to be run without spawning a task
> fix: pre-registration test bug

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- crates/clients/eigenlayer/src/client.rs
- crates/runners/eigenlayer/src/bls.rs
- crates/runners/eigenlayer/src/ecdsa.rs
- crates/runners/eigenlayer/src/lib.rs
Re-implements the EigenLayer ECDSA Runner logic that was previously removed. Also adds some missing tests to CI.
> feat: eigenlayer ecdsa runner

- crates/testing-utils/anvil/src/anvil.rs
Fixes EigenLayer test contract size limit issue
> fix(ci): eigen test contract size error

- .cursor/rules/general.mdc
- .gitignore
- Cargo.lock
- Cargo.toml
- README.md
- blueprints/incredible-squaring-eigenlayer/foundry.toml
- blueprints/incredible-squaring-eigenlayer/remappings.txt
- blueprints/incredible-squaring-eigenlayer/soldeer.lock
- cli/Cargo.toml
- cli/src/anvil/mod.rs
- cli/src/deploy/eigenlayer.rs
- cli/src/foundry/forge.rs
- cli/src/main.rs
- crates/networking/README.md
- crates/runners/eigenlayer/src/bls.rs
Please verify it runs for you @Tjemmmic
> Improve appearance and dev experience

- cli/src/deploy/tangle.rs
> fix(cli): allow contracts in workspace root

- crates/runner/src/lib.rs
- examples/incredible-squaring/incredible-squaring-bin/src/main.rs
- examples/incredible-squaring/incredible-squaring-lib/tests/e2e.rs
> fix: hide background service warnings if none are registered

- crates/tangle-extra/src/metadata/macros.rs
> fix: module job_definition is private error

- cli/src/command/deploy/eigenlayer.rs
- cli/src/tests/eigenlayer/deployment.rs
- cli/src/tests/eigenlayer/run.rs
- crates/chain-setup/anvil/src/anvil.rs
- crates/clients/eigenlayer/src/tests.rs
- crates/clients/evm/src/instrumented_client.rs
- crates/testing-utils/eigenlayer/src/harness.rs
> feat: return a struct from anvil container creation

- cli/README.md
- cli/src/command/keys.rs
- cli/src/main.rs
Fixes a small issue present in the CLIs key generate command and updates the README
> fix(cli): key generate and readme

- crates/evm-extra/src/producer/polling.rs
- crates/router/src/job_id_router.rs
- crates/router/src/routing.rs
- crates/runner/src/lib.rs
- crates/tangle-extra/src/consumer/mod.rs
- crates/tangle-extra/src/producer/mod.rs
Makes filtering and debugging much easier
> feat: add targets for some logs

- crates/runner/src/lib.rs
Just maintain a set of job futures instead of blocking on each call. They can still be completed in an arbitrary order
closes #808
> fix(runner): stop blocking on job calls

- Cargo.lock
- Cargo.toml
- crates/manager/Cargo.toml
- crates/manager/src/executor/event_handler.rs
- crates/manager/src/gadget/mod.rs
- crates/manager/src/sdk/utils.rs
- crates/manager/src/sources/binary.rs
- crates/manager/src/sources/container.rs
- crates/manager/src/sources/github.rs
- crates/manager/src/sources/mod.rs
- crates/manager/src/sources/testing.rs
- examples/incredible-squaring/Cargo.lock
> feat(manager): support container sources

- crates/manager/src/error.rs
- crates/manager/src/executor/event_handler.rs
> feat(manager)!: support multiple sources

- cli/src/main.rs
The keystore being generated manually before wasn't valid. Let the `Keystore` handle the directory creation. Also prompt for an sr25519 key, otherwise a Tangle blueprint won't run.
> fix(cli): construct a keystore for blueprint run

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- cli/src/tests/tangle/run.rs
- crates/manager/src/sources/testing.rs
- crates/networking/extensions/agg-sig-gossip/src/tests/mod.rs
- crates/std/src/io/error.rs
- crates/std/src/io/mod.rs
- crates/std/src/rand_helper.rs
- crates/stores/local-database/Cargo.toml
- crates/stores/local-database/src/lib.rs
- crates/testing-utils/tangle/src/blueprint.rs
This fixes issues in a handful of crates causing CI to fail
> fix(ci): cleanup tests in ci

- Cargo.lock
- Cargo.toml
- cli/src/command/run/tangle.rs
- cli/src/main.rs
- cli/src/tests/tangle/run.rs
- crates/manager/Cargo.toml
- crates/manager/src/config.rs
- crates/manager/src/error.rs
- crates/manager/src/executor/event_handler.rs
- crates/manager/src/executor/mod.rs
- crates/manager/src/main.rs
- crates/manager/src/sdk/utils.rs
- crates/manager/src/sources/binary.rs
- crates/manager/src/sources/container.rs
- crates/manager/src/sources/github.rs
- crates/manager/src/sources/mod.rs
- crates/manager/src/sources/testing.rs
- examples/incredible-squaring/Cargo.lock
> feat(manager)!: support verifying binaries with gh attestations

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- crates/auth/Cargo.toml
- crates/auth/src/api_tokens.rs
- crates/auth/src/db.rs
- crates/auth/src/lib.rs
- crates/auth/src/models.rs
- crates/auth/src/proxy.rs
- crates/auth/src/test_client.rs
- crates/auth/src/types.rs
- crates/macros/src/lib.rs
- examples/incredible-squaring/incredible-squaring-bin/src/main.rs
- flake.lock
This pull request introduces a new authentication module (`blueprint-auth`) for handling API tokens, along with several dependency updates in `Cargo.toml`. The most significant changes include the addition of the `blueprint-auth` crate, implementation of a token generator and validation system, and updates to dependencies to support these features.
* **Addition of `blueprint-auth` crate**: A new crate, `blueprint-auth`, is introduced to handle HTTP/WS authentication. It includes dependencies for cryptographic operations, token generation, and HTTP handling. (`crates/auth/Cargo.toml`, [crates/auth/Cargo.tomlR1-R50](diffhunk://#diff-30d3edbdde86555f871570813c965a21ddb4398cae87efab572ee07046218b9cR1-R50))
* **API Token Generator and Validation**: Implements `ApiTokenGenerator` for creating …
> feat: auth proxy

- cli/src/command/jobs/helpers.rs
- cli/src/command/service/request.rs
- cli/src/main.rs
- cli/src/tests/tangle/run.rs
- cli/src/tests/tangle/services.rs
> feat: add support for request params

- crates/sdk/src/lib.rs
> chore: document logging targets

- Cargo.lock
- crates/auth/Cargo.toml
- crates/auth/fixtures/bun.lock
- crates/auth/fixtures/package.json
- crates/auth/fixtures/sign.ts
- crates/auth/src/api_tokens.rs
- crates/auth/src/lib.rs
- crates/auth/src/models.rs
- crates/auth/src/proxy.rs
- crates/auth/src/types.rs
This pull request introduces several enhancements and fixes across the codebase, focusing on cryptographic signing and verification, improved logging and debugging, and better compatibility with external systems. The most significant changes include integrating new cryptographic libraries, adding structured logging with `tracing`, and ensuring compatibility between Rust and JavaScript implementations for cryptographic operations.
* Added comprehensive cryptographic signing and verification functionality using `@polkadot/keyring` and `@polkadot/util-crypto` libraries in `crates/auth/fixtures/sign.ts`. This includes ECDSA and Sr25519 key generation, signing, and request body construction for verification.
* Updated the `verify_challenge_sr25519` function to align with Substrate's signing …
> fix: change the schnorrkel ctx to substrate instead of tangle
