tangle-network/blueprint

Cargo.toml, gadget-core/src/job.rs, gadget-core/src/job_manager.rs, playground/examples/node.rs, test-gadget/src/gadget.rs, webb-gadget/src/helpers.rs, webb-gadget/src/lib.rs, zk-gadget/src/lib.rs, zk-gadget/src/module/mod.rs, zk-gadget/src/module/proto_gen.rs, zk-gadget/tests/jobs.rs
The purpose of this PR is to cleanup any rough edges inside the abstractions to allow making future gadgets easier and less repetitive.
=> Streamline and refactor

protocols/dfns-cggmp21/tests/ecdsa.rs, protocols/mp-ecdsa/tests/ecdsa.rs
CI has very limited resources, we do not want to test these tests on CI.
=> ci: ignore parallel jobs testing

Cargo.lock, shell-configs/local-testnet-0.toml, shell-configs/local-testnet-1.toml, shell-configs/local-testnet-2.toml, shell/Cargo.toml, shell/src/config.rs, shell/src/main.rs, shell/src/network/gossip.rs
This PR Imporves the gadget shell CLI to make it easier to work with, with sensible defaults.
```bash
Gadget 0.1.0
An MPC executor that connects to the Tangle network to perform work
USAGE:
gadget-shell [FLAGS] [OPTIONS] --base-path <base-path>
FLAGS:
-h, --help       Prints help information
--pretty     Whether to use pretty logging
-V, --version    Prints version information
-v, --verbose    The verbosity level, can be used multiple times
OPTIONS:
-d, --base-path <base-path>
The base path to store the shell data, and read data from the keystore
-i, --bind-ip <bind-ip>                        The IP address to bind to for the libp2p node [default: 0.0.0.0]
-p, --port <bind-port>                         The port to bind to for the libp2p node [default: 30555]
--bootnodes <bootnodes>... …
```
=> feat: Rework Gadget Shell CLI

common/src/client.rs, shell/src/shell.rs, shell/src/tangle.rs, test-utils/src/mock.rs
This PR adds a feature to automatically start and stop different protocols using the on-chain data based on the current restaker roles.
Closes #95
=> feat: watch for on-chain role changes

.cargo/config.toml, .github/workflows/validate_pr.yml, common/src/gadget/mod.rs, common/src/prometheus.rs, core/src/job.rs
We will need to run the ZkSaaS protocol in a beefier machine. The GitHub runners are too slow for it to reliably pass.
=> Disable ZkSaaS Pipeline + Metrics wrapper for jobs

Cargo.lock, Cargo.toml, cli/src/deploy.rs, cli/src/signer.rs, common/Cargo.toml, common/src/lib.rs, core/Cargo.toml, gadget-io/Cargo.toml, macros/blueprint-proc-macro-core/Cargo.toml, macros/blueprint-proc-macro/Cargo.toml, sdk/Cargo.toml, sdk/src/network/handlers/identify.rs, sdk/src/network/setup.rs, shell-sdk/src/lib.rs
This PR made it possible to publish our SDK to crates.io.
The list of published crates:
1. [gadget-core](https://crates.io/crates/gadget-core).
2. [gadget-common](https://crates.io/crates/gadget-common).
3. [gadget-io](https://crates.io/crates/gadget-io).
4. [gadget-blueprint-proc-macro-core](https://crates.io/crates/gadget-blueprint-proc-macro-core).
5. [gadget-blueprint-proc-macro](https://crates.io/crates/gadget-blueprint-proc-macro).
6. [gadget-sdk](https://crates.io/crates/gadget-sdk).
7. [blueprint-metadata](https://crates.io/crates/blueprint-metadata).
Note that we do now use the published crates of Polkadot SDK v1.7.0, instead of the ones that comes from github.
=> Publish Gadget SDK to crates.io

core/Cargo.toml, core/src/job_manager.rs
No WASM tests exist, `wasm_bindgen_test` is being setup unnecessarily.
=> Remove unnecessary WASM dependencies from `core`

cli/Cargo.toml, cli/src/main.rs
Fixes #225
Rename the Gadget CLI to Tangle CLI and update subcommands.
* **cli/Cargo.toml**
- Rename the package from `cargo-gadget` to `cargo-tangle`.
* **cli/src/main.rs**
- Update the `bin_name` attribute in the `clap` macro to `cargo-tangle`.
- Add a new subcommand `Gadget` to the `Commands` enum.
- Move the `Create` and `Deploy` subcommands under the `Gadget` subcommand.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/webb-tools/gadget/issues/225?shareId=8cf7fdf9-26dc-4155-bd46-0a5505d9330d).
=> Rename Gadget CLI to Tangle CLI

cli/README.md
Fixes #226
Add documentation for the Tangle CLI usage in the `cli/README.md` file.
* **Overview**: Add an overview section at the top of the `README.md` file.
* **Table of Contents**: Add an index at the top of the `README.md` file.
* **Installation**: Document how to install the CLI from crates.io.
* **Creating a New Blueprint/Gadget**: Document how to use the CLI to create a new blueprint/gadget.
* **Deploying the Blueprint**: Document how to use the CLI to deploy the blueprint to a local Tangle node.
* **Required Environment Variables**: Document the required ENVs for the deployment.
* **Examples**: Provide examples with each step and the expected output.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/webb-tools/gadget/issues/226?shar …
=> Add CLI usage documentation to README

Cargo.lock, common/Cargo.toml, common/src/lib.rs, core/Cargo.toml, environments/tangle/src/runtime.rs, gadget-io/Cargo.toml, sdk/Cargo.toml
This removes unused dependencies and sorts the tables.
`common` depended on `color-eyre` just to re-export it. That re-export was only used by `tangle-environment`, so I just made a new `common::Error` variant for it to use instead (https://github.com/webb-tools/gadget/commit/0d8e38e5397f59af81e2d63ed6dadf56754dc685). Outside of that, there are no functionality changes.
=> Cleanup unused dependencies

Cargo.lock, Cargo.toml, sdk/Cargo.toml, sdk/src/env.rs, sdk/src/events_watcher/mod.rs, sdk/src/keystore/backend/mem.rs, sdk/src/keystore/backend/mod.rs, sdk/src/keystore/bls381.rs, sdk/src/keystore/ecdsa.rs, sdk/src/keystore/ed25519.rs, sdk/src/keystore/error.rs, sdk/src/keystore/mod.rs, sdk/src/keystore/sr25519.rs, sdk/src/lib.rs, sdk/src/random.rs, sdk/src/slashing/reports.rs
Each commit message speaks for itself, the only major change is the addition of `GadgetEnvironment::load_with_lock<R>()` where `R` is `lock_api::RawRwLock`. This allows callers to bring their own lock in `no_std` environments. `GadgetEnvironment::load()` is now `std` only, and will use `parking_lot::RawRwLock` as before.
=> Make a subset of gadget-sdk no_std compatible

Cargo.lock, Cargo.toml, sdk/Cargo.toml, sdk/src/clients/mod.rs, sdk/src/events_watcher/error.rs, sdk/src/events_watcher/evm.rs, sdk/src/events_watcher/mod.rs, sdk/src/events_watcher/retry.rs, sdk/src/events_watcher/substrate.rs, sdk/src/lib.rs, sdk/src/mutex_ext.rs
`backoff` hasn't been updated in years, and `backon` supports `wasm32-unknown-unknown`. Most of the `events_watcher` module builds on WASM now.
Part of #189
=> sdk: Switch to `backon`

.github/workflows/ci.yml, sdk/src/benchmark/mod.rs, sdk/src/lib.rs
A lot of the SDK is WASM compatible, this enables the CI checks to make sure that it continues to stay that way. Additional features for WASM are on hold for now.
closes #189
=> Pause work on WASM support

.github/workflows/release-plz.yml
This PR adds [`Release plz`](https://release-plz.ieni.dev/) to our CI to manage releases and publish things to crates.io by just merging the release PR.
Part of #303
=> ci: Add Release-plz to the CI.

.github/workflows/release.yml, Cargo.toml
This fixes the issue while creating a github release which is already created by release-plz.
=> ci: do not create release from cargo-dist

Cargo.lock, blueprint-manager/src/cli.rs, macros/context-derive/Cargo.toml, macros/context-derive/src/cfg.rs, macros/context-derive/src/evm.rs, macros/context-derive/src/keystore.rs, macros/context-derive/src/lib.rs, macros/context-derive/src/subxt.rs, macros/context-derive/tests/tests.rs, macros/context-derive/tests/ui/01_basic.rs, macros/context-derive/tests/ui/02_unnamed_fields.rs, macros/context-derive/tests/ui/03_generic_struct.rs, sdk/src/ctx.rs, sdk/src/executor/mod.rs, sdk/src/lib.rs, sdk/src/metrics/mod.rs, sdk/src/store/mod.rs
This pull request introduces significant enhancements to the `macros/context-derive` crate by adding support for EVM and Tangle client contexts, refactoring existing code, and updating tests to cover new functionalities.
* Added dependencies for EVM-related functionality in `Cargo.toml`. (`macros/context-derive/Cargo.toml`)
* Introduced `EVMProviderContext` and `TangleClientContext` traits in the `gadget-sdk` crate. (`sdk/src/ctx.rs`)
* Split `cfg`, `evm`, `keystore`, and `subxt` modules into separate files for better modularity. (`macros/context-derive/src/lib.rs`)
* Refactored `find_config_field` function and `FieldInfo` enum into `cfg` module. (`macros/context-derive/src/cfg.rs`)
* Implemented `generate_context_impl` for `EVMProviderContext`. (`macros/context-derive/src/evm.rs`)
* …
=> feat: add EVM Provider and Tangle Client Context Extensions

.github/workflows/ci.yml, macros/context-derive/src/lib.rs, macros/context-derive/src/services.rs, macros/context-derive/tests/ui/01_basic.rs, macros/context-derive/tests/ui/02_unnamed_fields.rs, macros/context-derive/tests/ui/03_generic_struct.rs, sdk/src/ctx.rs, sdk/src/lib.rs
This pull request introduces a new `ServicesContext` trait and its corresponding derive macro to the `context-derive` crate, along with updates to existing test files to incorporate this new trait. The most important changes include adding the `ServicesContext` module, implementing the derive macro, generating the context implementation, and updating the test cases to use the new trait.
* [`macros/context-derive/src/lib.rs`](diffhunk://#diff-20cccca6733ac2e3b3a8c7b201c2947890985b62696cba77ce377b45fd66dc8eR20-R21): Added the `services` module and implemented the `derive_services_context` function to generate the `ServicesContext` trait implementation. [[1]](diffhunk://#diff-20cccca6733ac2e3b3a8c7b201c2947890985b62696cba77ce377b45fd66dc8eR20-R21) …
=> feat: add ServicesContext Extension

Cargo.lock, Cargo.toml, gadget-io/Cargo.toml
Removes the Git dependencies from `thiserror` and `url` that were leftover from `no-std` compatibility work.
=> Removes Remaining Git Dependencies

Cargo.toml, cli/Cargo.toml
fix the issue where the CLI package does not have description, which prevents it from being published.
=> chore: add CLI description to Cargo.toml

sdk/src/config.rs
Since the blueprint template now supports generating `Dockerfile`s, this makes it a little simpler.
For now, the blueprint template uses an entrypoint script to use env vars as arguments: https://github.com/webb-tools/blueprint-template/blob/main/docker/entrypoint.sh
This makes it possible to just have the binary as the entrypoint without having to rebuild the image when changing arguments.
=> feat: allow env vars for `ContextConfig` args

cli/src/signer.rs
`SecretUri.junctions` was ignored, returning the wrong keypair for `SIGNER="//Alice"`.
=> fix: load substrate signer from env correctly

blueprint-manager/src/config.rs, blueprint-manager/src/executor/mod.rs, blueprint-manager/src/main.rs, blueprint-manager/src/sources/mod.rs, blueprint-test-utils/src/lib.rs, sdk/src/config.rs
It was (mistakenly?) removed in #333. Went ahead and added a default path for blueprint manager as well.
=> fix: add `data_dir` back to `GadgetConfiguration`

blueprint-metadata/src/lib.rs
I'm trying to build a blueprint against the main branch
=> fix: uncomment generate_json

cli/src/create.rs, cli/src/main.rs
Part of #352, committing it now since it works and I'd like to have it on all my branches.
=> feat(cli): support custom repo and path sources

Cargo.lock, Cargo.toml, blueprint-manager/src/executor/mod.rs, blueprint-test-utils/src/lib.rs, blueprint-test-utils/src/test_ext.rs, gadget-io/src/imp/standard/keystore.rs, macros/blueprint-proc-macro/src/event_listener/tangle.rs, macros/blueprint-proc-macro/src/job.rs, macros/blueprint-proc-macro/src/report.rs, sdk/src/clients/tangle/services.rs, sdk/src/config.rs, sdk/src/events_watcher/substrate.rs, sdk/src/job_runner.rs, sdk/src/keystore/backend/mod.rs, sdk/src/keystore/mod.rs, sdk/src/lib.rs
It's currently impossible to use some APIs downstream, since they expose `sp_core` (v0.34.0) types instead of the `sdk::keystore::sp_core_subxt` (v0.31.0) types. Cargo will refuse to build blueprints using them. I just got rid of the `sdk::keystore::sp_core_subxt` hack and downgraded all of the dependencies necessary (I think).
This won't be an issue once #318 is taken care of.
I also re-exported `libp2p` for convenience.
=> fix(sdk)!: downgrade substrate dependencies for now

sdk/src/config.rs
Right now they're just getting passed in and immediately discarded.
=> feat: expose bootnodes in GadgetConfiguration

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, blueprint-metadata/src/lib.rs, blueprint-test-utils/src/anvil.rs, blueprint-test-utils/src/lib.rs, blueprints/incredible-squaring-eigenlayer/src/lib.rs, cli/src/create.rs, sdk/Cargo.toml, sdk/src/keystore/backend/fs.rs, sdk/src/keystore/backend/mem.rs, sdk/src/keystore/backend/mod.rs, sdk/src/keystore/bn254.rs, sdk/src/keystore/mod.rs, sdk/src/keystore/sr25519.rs, sdk/src/keystore/tests.rs
Addresses/adds the following:
- Support for EigenLayer keys i.e., BLS BN254
- Fixes for BLS BN254, and BLS381
- Tests for all keystore types and key types
=> fix(sdk): updated keystore support and fixes

.github/workflows/release-plz.yml
This pull request includes a small but important change to the `.github/workflows/release-plz.yml` file. The change updates the `MarcoIeni/release-plz-action` to a specific commit hash for better version control.
* Updated the `MarcoIeni/release-plz-action` to use a specific commit hash `91356927c5ac06a27d9342861ff6e234210d56b4` instead of the version tag `v0.5`. (`.github/workflows/release-plz.yml`)
Related to this comment: https://github.com/MarcoIeni/release-plz/issues/1791#issuecomment-2432360669
=> ci: downgrade and pin release-plz

Cargo.lock, Cargo.toml, blueprint-metadata/Cargo.toml, macros/blueprint-proc-macro/src/job.rs
This pull request makes several changes to the `macros/blueprint-proc-macro/src/job.rs` file to clean up the code by removing unnecessary `#[derive(Debug)]` annotations. The most important changes include:
Code cleanup:
* `impl Parse for Results` in `macros/blueprint-proc-macro/src/job.rs`: Removed the `#[derive(Debug)]` annotation from the `EventListenerArgs` struct.
* `pub enum ListenerType` in `macros/blueprint-proc-macro/src/job.rs`: Removed the `#[derive(Debug)]` annotation from the `SingleListener` struct.
* `impl Parse for EventListenerArgs` in `macros/blueprint-proc-macro/src/job.rs`: Removed the `#[derive(Debug)]` annotation from the `EvmArgs` struct.
=> chore: release crates manually to unblock release-plz

blueprints/incredible-squaring/src/main.rs, blueprints/periodic-web-poller/src/main.rs, sdk/src/error.rs, sdk/src/job_runner.rs
Jobs can be built using tuples now. Some comparisons:
```rust
MultiJobRunner::new(&env)
.with_job()
.with_default_price_targets()
.finish(x_square)
```
```rust
MultiJobRunner::new(&env)
.job(x_square)
```
```rust
use tangle_subxt::tangle_testnet_runtime::api::runtime_types::tangle_primitives::services::PriceTargets;
let price_targets = PriceTargets {
cpu: 5,
mem: 10,
storage_hdd: 15,
storage_ssd: 20,
storage_nvme: 25
};
MultiJobRunner::new(&env)
.with_job()
.with_price_targets(price_targets)
.finish(x_square)
```
```rust
use tangle_subxt::tangle_testnet_runtime::api::runtime_types::tangle_primitives::services::PriceTargets;
let price_targets = PriceTargets {
cpu: 5,
mem: 10,
storage_hdd: 15,
storage_ssd: 20,
storage_nvme: 25
};
MultiJobRunner::new(env)
.job((x_square2, price_targets))
``` …
=> feat(gadget-sdk): improve `MultiJobRunner` builder

README.md, cli/README.md, cli/src/main.rs
Also added "bp" as an alias since blueprint is a long word.
closes #353
=> feat(cargo-tangle)!: rename "gadget" to "blueprint"

Cargo.lock, blueprints/incredible-squaring-eigenlayer/Cargo.toml, blueprints/incredible-squaring-eigenlayer/build.rs
Blueprint Metadata is not needed for the Eigenlayer Blueprints and is causing issues in the build script. This PR removes it from the incredible-squaring-eigenlayer blueprint.
=> fix(blueprints): remove blueprint metadata from eigen blueprint

Cargo.lock, Cargo.toml, sdk/Cargo.toml, sdk/src/docker.rs, sdk/src/error.rs, sdk/src/lib.rs
This will be useful for multiple blueprints since interacting with Docker programmatically like this gets repetitive. It can also easily be extended in the future, when blueprints come to need extra features.
This is taken from the Obol blueprint:
```rust
let mut container = Container::new(&self.docker, IMAGE.to_string());
container
.cmd(vec!["dkg", "--publish"])
.binds(vec![format!("{}:{CHARON_DATA}", self.data_dir.display())]);
container.start(true).await?;
container.remove().await?;
```
**Also note that each new method has an example in the docs**
closes #373
=> feat(gadget-sdk): add utilities for interacting with Docker

Cargo.lock, Cargo.toml, blueprint-manager/Cargo.toml, blueprint-manager/src/config.rs, blueprint-manager/src/main.rs, blueprint-manager/src/sdk/entry.rs, blueprint-test-utils/src/lib.rs, blueprints/incredible-squaring-eigenlayer/Cargo.toml, blueprints/incredible-squaring-eigenlayer/src/runner.rs, blueprints/incredible-squaring/Cargo.toml, blueprints/periodic-web-poller/Cargo.toml, cli/src/create.rs, cli/src/keys.rs, cli/src/main.rs, gadget-io/Cargo.toml, gadget-io/src/imp/standard/shell.rs, gadget-io/src/shared/shell.rs, macros/blueprint-proc-macro/src/lib.rs, macros/blueprint-proc-macro/src/sdk_main.rs, sdk/Cargo.toml, sdk/src/config.rs, sdk/src/keystore/backend/mod.rs, sdk/src/lib.rs
This pull request includes a series of changes primarily focused on replacing `structopt` with `clap` for command-line argument parsing across multiple files and projects. Additionally, there are some minor refactors and updates to dependencies and configurations.
**Migration from `structopt` to `clap`:**
* [`blueprint-manager/src/config.rs`](diffhunk://#diff-c23486c3b14b30ae524c0c7d1c94bc5c96d50ec83becd39c3c4020d199851341R1-R29): Replaced `structopt` with `clap` for parsing command-line arguments in `BlueprintManagerConfig`. Updated attribute macros accordingly.
* [`blueprint-manager/src/main.rs`](diffhunk://#diff-5af4b69b114fb86eec2f4094f227a6b0d7238f77da8c3592c33174631e99ce3eR5-R13): Updated the usage of `BlueprintManagerConfig` to use `clap`'s `parse` method instead of `structopt`'s …
=> fix(cargo-tangle): CLI bugs

macros/blueprint-proc-macro/Cargo.toml
Looks like if you just use a path dependency (or a dependency in any way that doesn't specify a version), then it'll just get dropped from the manifest when publishing.
closes #388
=> fix(blueprint-proc-macro): resolve dependency cycle with gadget-sdk

sdk/src/error.rs, sdk/src/executor/mod.rs, sdk/src/executor/process/error.rs, sdk/src/executor/process/manager.rs, sdk/src/executor/process/mod.rs, sdk/src/executor/process/types.rs, sdk/src/executor/process/utils.rs
We really shouldn't be using `Box<dyn Error>` anywhere in the SDK.
=> feat!(gadget-sdk): add an Error type for executor module

release-plz.toml
Part of #372
This comes with some new rules for our commit messages.
For commits we don't want getting into changelogs.
* CI changes
* Use a scope of "ci": `feat(ci): ...`
* Clippy fixes
* Use a scope or description of "clippy":
* `chore(clippy): ...`
* `chore: clippy`
* `chore(sdk): clippy`
* Formatting fixes
* Use a description of "fmt": `chore: fmt` or `chore(sdk): fmt`
* Dependency changes
* Use a scope of "deps": `chore(deps): ...`
* Using conventional commits in general
* This even applies to squashed commits
* Correctly marking things as breaking: `feat!:` vs `feat:`
* Splitting up our PRs
* At the moment, a lot of the PRs end up touching things outside of their scope.
* **Adding scopes to commit messages**
=> feat(ci): add some commit parsers to release-plz

blueprint-manager/src/executor/event_handler.rs, blueprint-manager/src/sources/mod.rs, macros/context-derive/src/services.rs, sdk/src/config/gadget_config.rs, sdk/src/config/mod.rs, sdk/src/config/protocol.rs, sdk/src/network/gossip.rs, sdk/src/runners/tangle.rs
This pull request includes several changes to the `sdk` module to improve the handling of `service_id` and streamline the configuration process for Tangle blueprints. The most important changes include making `service_id` optional, adjusting related methods, and removing redundant checks.
Changes to `service_id` handling:
* [`sdk/src/config/gadget_config.rs`](diffhunk://#diff-19106a76235604808c349482ef99f5f7d6a2b4bde9ba373ea1cbcadd8d642f0dL111-R111): Modified `service_id` to be optional in `GadgetConfiguration` and updated the `service_id` method to return the correct type. [[1]](diffhunk://#diff-19106a76235604808c349482ef99f5f7d6a2b4bde9ba373ea1cbcadd8d642f0dL111-R111) [[2]](diffhunk://#diff-19106a76235604808c349482ef99f5f7d6a2b4bde9ba373ea1cbcadd8d642f0dL216-R216)
* …
=> fix(sdk)!: allow for zero-based `blueprint_id`

sdk/src/event_listener/tangle/mod.rs
This pull request includes an improvement to the `ValueIntoFieldType` implementation in the `sdk/src/event_listener/tangle/mod.rs` file. The main change is the addition of a type check to handle `Vec<u8>` more efficiently and safely.
Enhancements to `ValueIntoFieldType` implementation:
* Added a type check for `Vec<u8>` in the `ValueIntoFieldType` implementation to convert it directly to `Field::Bytes` using `Vec::from_raw_parts`, ensuring proper memory management and avoiding double-freeing issues.
Note that this a hot-fix, to get myself unblocked in my current task. However this won't be needed once #424 is fully implemented.
Closes #427
=> fix(sdk): Return `Bytes` when using `Vec<u8>` in params and result

blueprint-build-utils/Cargo.toml, blueprint-serde/Cargo.toml, blueprint-test-utils/Cargo.toml
This pull request includes updates to the `Cargo.toml` files of several packages to add descriptions and modify the publish settings. The most important changes include adding descriptions to the packages and setting the `publish` attribute to `false` for certain packages.
Updates to package descriptions:
* [`blueprint-build-utils/Cargo.toml`](diffhunk://#diff-c58966cde75cf027a9ef41416e508ed65536c76b27495f4c7ada5a005a65ae40R4-R10): Added description "Tangle Blueprint build utils".
* [`blueprint-serde/Cargo.toml`](diffhunk://#diff-121573d071b609976749a70d075ea45faace82116bd50b0c6a967e2211ddd30eR4): Added description "Tangle Blueprints serde integration".
* [`blueprint-test-utils/Cargo.toml`](diffhunk://#diff-ef317052248e4c3812ee440fede2706ea12802e7a10b3d4d2fd4a8bfbb280e42R5): Added …
=> chore: add description to crates

macros/context-derive/Cargo.toml
This pull request includes changes to the `Cargo.toml` file for the `context-derive` macro.
Dependency updates:
* Changed the `gadget-sdk` dependency from a workspace reference to a path reference in `macros/context-derive/Cargo.toml`
Related to #388
=> fix: cyclic dependencies between context-derive and sdk

blueprint-test-utils/src/lib.rs, sdk/src/network/gossip.rs, sdk/src/network/handlers/connections.rs, sdk/src/network/handlers/dcutr.rs, sdk/src/network/handlers/gossip.rs, sdk/src/network/handlers/identify.rs, sdk/src/network/handlers/mdns.rs, sdk/src/network/handlers/p2p.rs, sdk/src/network/handlers/ping.rs, sdk/src/network/handlers/relay.rs
This pull request includes several changes aimed at improving the logging granularity and updating the job completion mechanism in the `blueprint-test-utils` and `sdk` modules.
* [`sdk/src/network/gossip.rs`](diffhunk://#diff-eaa31da1831a49959d61586dde5384769520acbbe1476224c7abb52e4884e930L160-R160): Replaced `debug` logging with `trace` logging for various network events to provide more detailed logs. [[1]](diffhunk://#diff-eaa31da1831a49959d61586dde5384769520acbbe1476224c7abb52e4884e930L160-R160) [[2]](diffhunk://#diff-eaa31da1831a49959d61586dde5384769520acbbe1476224c7abb52e4884e930L229-R229)
* [`sdk/src/network/handlers/connections.rs`](diffhunk://#diff-2ecadd63691535c8527fb5b7ce03ba46e015323f2945b083b59c73bb21819d28L15-R15): Updated several log statements from `debug` to `trace` to …
=> chore: improve test-utils and lower networking log level

Cargo.toml, macros/blueprint-proc-macro/src/sdk_main.rs, sdk/src/runners/mod.rs, sdk/src/runners/tangle.rs
This pull request includes several updates to dependencies, submodules, and error handling in the project. The most important changes are the addition of a new dependency, updates to submodule commits, and improvements in error handling and function implementation.
Dependency updates:
* Added `eyre` version `0.6.12` to `Cargo.toml` to enhance error reporting capabilities.
Error handling improvements:
* Added a new error variant `NotActiveOperator` to the `RunnerError` enum in `sdk/src/runners/mod.rs` to handle cases where the operator is not active.
* Modified `impl BlueprintConfig for TangleConfig` in `sdk/src/runners/tangle.rs` to check if the operator is active and return the new `NotActiveOperator` error if not.
Function implementation improvements:
* Updated `sdk_main_impl` function …
=> fix: handle edge cases during registration

blueprint-test-utils/Cargo.toml, blueprint-test-utils/src/lib.rs, blueprint-test-utils/src/tangle.rs
This pull request introduces several significant changes to the `blueprint-test-utils` crate, including making the crate publishable, adding a new module, and implementing a new utility for running Tangle nodes. The most important changes are outlined below:
* Updated `Cargo.toml` to make the crate publishable by setting `publish = true`.
* Added a new module `tangle` to the `blueprint-test-utils` crate.
* Implemented a new utility in `blueprint-test-utils/src/tangle.rs` for configuring and running Tangle nodes. This includes defining the `SubstrateNodeBuilder` and `SubstrateNode` structs, various methods for setting up and managing nodes, and error handling.
I've been using this in my blueprint and it looks useful to be here in the test-utils.
=> feat: add Substrate Node Runner to blueprint-test-utils

blueprint-manager/Cargo.toml, blueprint-test-utils/Cargo.toml
This pull request includes changes to the `Cargo.toml` files for the `blueprint-manager` and `blueprint-test-utils` packages to utilize workspace settings for various metadata fields.
Changes to `blueprint-manager`:
* [`blueprint-manager/Cargo.toml`](diffhunk://#diff-dd70089194a21e881d628a3f5773cb2737b6b313d83c831df04ac88d836f71f8L4-R9): Added workspace settings for `authors`, `edition`, `homepage`, `repository`, and `license`, and updated the `description` field.
Changes to `blueprint-test-utils`:
* [`blueprint-test-utils/Cargo.toml`](diffhunk://#diff-ef317052248e4c3812ee440fede2706ea12802e7a10b3d4d2fd4a8bfbb280e42L4-R9): Added workspace settings for `authors`, `edition`, `homepage`, `repository`, and `license`.
=> chore: set blueprint-manager publishable

sdk/src/docker.rs, sdk/src/error.rs, sdk/src/lib.rs
* `Container::from_id` - Lookup an existing container based on its ID
* `Container::status` - Get the status of a container (created, running, dead, etc)
* Env vars not actually being passed to containers
* Changed the type of `gadget_sdk::Error::Docker`
=> feat(gadget-sdk)!: add more Docker utils

Cargo.lock, Cargo.toml, blueprint-serde/Cargo.toml, blueprint-serde/src/de.rs, blueprint-serde/src/lib.rs, blueprint-serde/src/ser.rs, blueprint-serde/src/tests.rs, macros/blueprint-proc-macro/src/shared.rs, sdk/src/lib.rs
With `Field::List` and `Field::Bytes` being distinct types, we'll have to rely on `serde_bytes::ByteBuf` to call the `serialize_byte_buf` method. That means any job returning `Vec<u8>` should now return `ByteBuf`, which has been re-exported in the SDK.
Simply:
```rust
fn my_job() -> Result<Vec<u8>> {
Ok(some_vec)
}
```
To:
```rust
use gadget_sdk::ByteBuf;
fn my_job() -> Result<ByteBuf> {
Ok(some_vec.into())
}
```
=> fix(gadget-blueprint-serde)!: handle bytes properly

Cargo.lock, Cargo.toml, blueprint-test-utils/src/eigenlayer_test_env.rs, blueprint-test-utils/src/helpers.rs, blueprints/examples/src/eigen_context.rs, blueprints/incredible-squaring-eigenlayer/src/contexts/aggregator.rs, blueprints/incredible-squaring-eigenlayer/src/contexts/client.rs, blueprints/incredible-squaring-eigenlayer/src/jobs/compute_x_square.rs, blueprints/incredible-squaring-eigenlayer/src/jobs/initialize_task.rs, blueprints/incredible-squaring-eigenlayer/src/lib.rs, blueprints/incredible-squaring-eigenlayer/src/tests.rs, blueprints/incredible-squaring-symbiotic/Cargo.toml, macros/context-derive/src/eigenlayer.rs, macros/context-derive/src/evm.rs, sdk/Cargo.toml, sdk/src/config/context_config.rs, sdk/src/config/mod.rs, sdk/src/config/protocol.rs, sdk/src/contexts/eigenlayer.rs, sdk/src/event_listener/tangle/jobs.rs, sdk/src/lib.rs, sdk/src/runners/eigenlayer.rs, sdk/src/runners/mod.rs, sdk/src/utils/evm.rs
And with it, the alloy dependencies.
**Also added a `symbiotic` feature to the SDK, `symbiotic-rs` will need to have its alloy dependency versions changed**
Draft for now, this required changing quite a bit, need to make sure it's all good.
closes #478
=> chore!: update `eigensdk`

Cargo.lock, Cargo.toml
Makes it possible to publish `blueprint-serde`, and then `gadget-sdk`.
closes #511
=> chore!: update `tangle-subxt`

Cargo.lock, blueprint-test-utils/src/lib.rs, blueprint-test-utils/src/tangle/mod.rs, blueprint-test-utils/src/test_ext.rs, blueprints/incredible-squaring/Cargo.toml, blueprints/incredible-squaring/tests/e2e.rs
This moves the `manifest_path` fetching and Tangle node startup to `new_test_ext_blueprint_manager`. This process doesn't change between blueprints.
The `incredible-squaring` test has also been moved into the blueprint itself, rather than inside `blueprint-test-utils`.
=> refactor(blueprint-test-utils)!: remove `Opts` boilerplate

.gitmodules
The submodule isn't there so Dependabot gets tripped up.
=> chore: remove nonexistent submodule

blueprint-metadata/src/lib.rs, macros/blueprint-proc-macro-core/src/lib.rs, macros/blueprint-proc-macro/src/job.rs
This PR is for debugging and fixing bugs as I see them.
For example, I got this error when submitting a keygen (job_id=0):
`Failed to submit job: Runtime(Module(ModuleError(<Services::TypeCheck>)))`
When I checked the generated blueprint.json, the keygen job was the second element. So, when I set the job IDs to be in order with the blueprint.json file, that error went away. The real fix is to ensure the listed jobs are sorted by ID.
=> fix(blueprint-proc-macro): fix bug where job IDs are not written in order to blueprint.json

blueprint-build-utils/src/lib.rs
- Build script doesn't unnecessarily run
- Soldeer runs install before updating
=> fix(blueprint-build-utils): build utils only run when necessary

crates/stores/local-database/src/lib.rs
It's an unnecessary bound, just adds friction
=> chore(stores): remove `Default` bound on `LocalDatabase`

Cargo.lock, crates/blueprint/metadata/Cargo.toml, crates/blueprint/metadata/src/lib.rs
This only adds error messages for some cases. Many others are still just panics.
This also fixes the issue of missing metadata producing an empty `BlueprintMetadata` and allowing the crate to continue building. It's now a hard error.
Removing the metadata from `incredible-squaring` yields:
```
warning: incredible-squaring-blueprint@0.1.1: Failed to generate blueprint metadata: Blueprint metadata not found in the Cargo.toml
error: failed to run custom build command for `incredible-squaring-blueprint v0.1.1 (<path>/blueprints/incredible-squaring)`
Caused by:
process didn't exit successfully: `<path>/target/debug/build/incredible-squaring-blueprint-a1eaf06037a611fc/build-script-build` (exit status: 1)
--- stdout
cargo:rerun-if-changed=src/lib.rs
cargo:rerun-if-changed=src/main.rs
Adding test …
```
=> feat(blueprint-metadata): nicer errors

crates/config/src/lib.rs, crates/macros/context-derive/tests/ui/basic.rs, crates/macros/context-derive/tests/ui/generic_struct.rs, crates/macros/context-derive/tests/ui/unnamed_fields.rs, crates/macros/playground/src/lib.rs
Historic type alias, no longer needs to exist
=> refactor: remove `StdGadgetConfiguration`

.cursor/rules/macro.mdc, crates/networking/src/tests/blueprint_protocol.rs, crates/testing-utils/core/src/runner.rs, crates/testing-utils/eigenlayer/src/runner.rs, crates/testing-utils/tangle/src/multi_node.rs, crates/testing-utils/tangle/src/runner.rs
1. Adds tests for a blueprint_protocol p2p/gossip protocol. Completely honest protocol.
1.  Generate random number
2. Gossip
3. Everyone sums it
4. Everyone sends summation and verifies.
2. Makes test struct parameters public, we currently can't get keystore from a handle just the `TanglePairSigner<sr25519>` key which is restrictive.
=> feat: get blueprint protocol basic summation gossip working

crates/sdk/Cargo.toml
This pull request includes a small change to the `crates/sdk/Cargo.toml` file. The change adds the `blueprint-runner?/networking` feature to the list of networking dependencies.
* [`crates/sdk/Cargo.toml`](diffhunk://#diff-f43d2be11323bdce102d0733ead2bfde8104dd6f2fc3b4329c8a7eccda26c73bR111): Added `blueprint-runner?/networking` to the `networking` list.
=> chore: enable `networking` for the blueprint-runner from the SDK.

crates/macros/tests/debug_job/fail/argument_not_extractor.stderr, crates/tangle-extra/src/extract/result.rs, crates/tangle-extra/src/metadata/job_definition.rs
This pull request includes several changes to the `tangle-extra` crate, focusing on adding new implementations for `IntoTangleFieldTypes` and expanding test coverage. The most important changes include adding implementations for `Result` and `Option` types, and adding new test cases for context-aware functions.
* Added implementations for `IntoTangleFieldTypes` for `Result` and `Option` types in `macro_rules! impl_tangle_field_types` in `crates/tangle-extra/src/extract/result.rs`.
* Added new context-aware test functions `[<$func _with_context_ret_res>]` and `[<$func _with_context_ret_opt>]` to `mod tests` in `crates/tangle-extra/src/metadata/job_definition.rs`.
* Included additional assertions for the new context-aware test functions in `mod tests` in …
=> feat: impl `IntoTangleFieldTypes` for `TangleResult` in `Result` and `Option`

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/src/deploy/tangle.rs, examples/incredible-squaring/Cargo.lock
This actually fixes 2 issues:
1. We were calling `escargot::CargoBuild::run()`, which isn't correct for the new workspace layout of Tangle blueprints. That causes CI to fail.
2. When a build failed, you had no idea why. Just a generic "Failed to build the package" message.
I guess this just wasn't encountered since I always have a `blueprint.json` from building the binary myself.
The new output is:
```
ERROR cargo_tangle::deploy::tangle: Cargo build failed
ERROR cargo_tangle::deploy::tangle: NOTE: Use `RUST_LOG=build-output=debug` to see more details
Error: 
0: Runner setup failed: Cargo build failed
```
Then with the suggestion:
```
DEBUG build-output:    Compiling hyperlane-validator-blueprint-bin v0.1.0 (hyperlane-validator-blueprint/hyperlane-validator-bin)
DEBUG build-output: error: …
```
=> feat: log build output

cli/src/deploy/tangle.rs, crates/tangle-extra/src/util/tests.rs, crates/testing-utils/core/src/runner.rs, crates/testing-utils/eigenlayer/src/runner.rs, crates/testing-utils/tangle/src/harness.rs, crates/testing-utils/tangle/src/multi_node.rs, crates/testing-utils/tangle/src/runner.rs, crates/testing-utils/tangle/src/tests.rs, examples/incredible-squaring/incredible-squaring-lib/tests/e2e.rs
The BLS blueprint, since it has networking in the context, needs to be able to set a context per-node, rather than once when the harness is created.
This changes `MultiNodeTestEnv::start()` to take a context, which will be cloned to each node, and adds `MultiNodeTestEnv::start_with_contexts()`, which takes a `Vec<Ctx>` to apply to the nodes in order.
```rust
use blueprint_core::extract::Context;
use gadget_tangle_testing_utils::TangleTestHarness;
use tempfile::TempDir;
// This context is node specific. Each node needs its own copy.
#[derive(Clone)]
struct MyContext {
foo: u64,
}
async fn some_job(Context(_context): Context<MyContext>) {}
// Start up a test with 2 nodes
const N: usize = 2;
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
let tmp_dir = …
```
=> feat(testing-utils): support per-node contexts

Cargo.lock, Cargo.toml, crates/clients/evm/src/instrumented_client.rs, crates/sdk/src/error.rs, examples/incredible-squaring/Cargo.lock
* bump `alloy` to 0.12
* bump `eigensdk` to the latest state of ***my branch***. Continuing to use my branch as a safety net until a new `eigensdk` release is out.
closes #740
=> chore: update alloy & eigensdk

Cargo.lock, crates/tangle-extra/src/metadata/macros.rs, flake.lock
closes #766
This pull request includes significant updates to the `blueprint_inner` macro in the `crates/tangle-extra/src/metadata/macros.rs` file to improve the handling and serialization of parameters. Additionally, it introduces new test cases to ensure the correctness of these updates.
Improvements to parameter handling and serialization:
* [`crates/tangle-extra/src/metadata/macros.rs`](diffhunk://#diff-70c90534f01433ac1ee4898f4411de0aed5bba57682b425eb116748d298ccb54L357-R370): Updated the `blueprint_inner` macro to generate and serialize `registration_params` and `request_params` using the `IntoTangleFieldTypes` trait.
Enhancements to testing:
* [`crates/tangle-extra/src/metadata/macros.rs`](diffhunk://#diff-70c90534f01433ac1ee4898f4411de0aed5bba57682b425eb116748d298ccb54R407-R422): …
=> feat: add support for `request_params` and `registration_params`

crates/chain-setup/tangle/src/transactions.rs, crates/testing-utils/tangle/src/harness.rs
This pull request introduces several updates to the `transactions.rs` and `harness.rs` files in the `tangle` crate, adding new parameters and functions to improve service setup and request handling. The most important changes include the addition of `RequestArgs` and `RegistrationArgs` parameters, and the creation of a new `SetupServicesOpts` struct.
* [`crates/chain-setup/tangle/src/transactions.rs`](diffhunk://#diff-2badf598962163a40ed251b077f99f8bad86d6f953584b11cc7f6e4642d7a6bfR35): Added `RequestArgs` parameter to the `request_service` and `setup_operator_and_service_multiple` functions to allow for more detailed service requests. [[1]](diffhunk://#diff-2badf598962163a40ed251b077f99f8bad86d6f953584b11cc7f6e4642d7a6bfR35) [[2]](diffhunk://#diff-2badf598962163a40ed251b077f99f8bad86d6f95 …
=> feat: add support for request and registration args in the test harness

crates/tangle-extra/src/metadata/job_definition.rs, crates/testing-utils/tangle/src/harness.rs, crates/testing-utils/tangle/src/multi_node.rs
Closes #778
This pull request includes an addition to the `crates/tangle-extra/src/metadata/job_definition.rs` file. The change implements the `IntoTangleFieldTypes` trait for the `Void` type from `blueprint_core::job_result`.
Key change:
* Added an implementation of the `IntoTangleFieldTypes` trait for the `Void` type, which returns a vector containing `FieldType::Void`.
=> feat: impl IntoTangleFieldTypes for Void

Cargo.lock, Cargo.toml
Uses an `eigensdk-rs` fork that resolves the reader type annotation error on nightly.
Allows `cargo-tangle` to be installed.
=> fix: use eigensdk fork

cli/src/command/deploy/mbsm.rs, cli/src/command/deploy/mod.rs, cli/src/main.rs
This pull request introduces a new feature to deploy the Master Blueprint Service Manager (MBSM) contract to the Tangle Network. The changes include the addition of a new command, necessary imports, and the implementation of the deployment logic.
Key changes include:
* [`cli/src/command/deploy/mbsm.rs`](diffhunk://#diff-d64280036730815ccaef4af414494a85303d623322f24a92f87e6b3ad49f373cR1-R115): Implemented the `deploy_mbsm` function to handle the deployment of the MBSM contract, including setting up the environment, checking for existing deployments, and deploying the contract if necessary.
* [`cli/src/command/deploy/mod.rs`](diffhunk://#diff-49d413c8ed499ee753b49cf25612f3d38f9a9c6cfe0dd47817e7cb7969dfb67fR2): Added the `mbsm` module to the list of deploy commands.
* …
=> feat: impl MBSM deploy subcommand

crates/tangle-extra/src/serde/error.rs, crates/tangle-extra/src/serde/ser.rs, crates/tangle-extra/src/serde/tests.rs
This just converts maps into unnamed `Field::Struct`s. That means that map keys must be strings.
So we don't *really* support maps, this is really just a hack for supporting JSON object conversions.
=> feat(blueprint-serde): partial map support

Cargo.lock, cli/Cargo.toml, cli/src/command/jobs/helpers.rs
Using our `blueprint_serde` would make things more easier to work with in the future.
---
This pull request includes significant changes to the `cli/src/command/jobs/helpers.rs` file, primarily to improve the handling of job arguments and simplify the codebase. The most important changes include adding new imports, refactoring the `load_job_args_from_file` function to use a more concise approach for parsing arguments, and improving error handling.
Improvements to argument parsing and error handling:
* [`cli/src/command/jobs/helpers.rs`](diffhunk://#diff-d7f6f99b1e6d83c89dbe474542f982a31d8aa55d2d57009fbd80807af0676695L2-R8): Added new imports `to_field` and `bail` to streamline the parsing process and improve error handling.
* [`cli/src/command/jobs/helpers.rs`](diffhunk://#diff-d7f6f99b1e6 …
=> feat: support all field types in the job submit subcommand

crates/core/src/macros.rs
This pull request includes changes to the `crates/core/src/macros.rs` file to update the logging target and modify the handling of job results in rejection macros. The most important changes are as follows:
Updates to logging target:
* Changed the logging target from `"gadget::rejection"` to `"blueprint-rejection"` in the `__log_rejection` macro.
Modifications to job result handling:
* Updated the `__define_rejection` macro to return a `JobResult::Err` with a new error instance instead of calling `into_job_result` on the body text. This change was applied in two places within the macro. [[1]](diffhunk://#diff-9f9d78b0be0c65a06b06bd5419f768554061d5af427860a9baa1d7b4be19dcb8L237-R237) [[2]](diffhunk://#diff-9f9d78b0be0c65a06b06bd5419f768554061d5af427860a9baa1d7b4be19dcb8L288-R288)
---- …
=> fix: job call rejections should be errors

crates/runner/src/lib.rs
Refactor job call processing to utilize tokio's async task spawning, improving concurrency and responsiveness. Adjust error handling to ensure proper logging of producer errors.
Completes #809
=> fix(blueprint-runner): update job call handling to use async tasks

Cargo.lock, Cargo.toml, flake.lock
This pull request includes updates to the `Cargo.toml` file to ensure compatibility with the latest versions of dependencies. The most important changes involve updating the versions of several dependencies to use more flexible version constraints.
Dependency updates:
* Updated `tokio` version to `^1` to allow for any compatible version within the major version 1.
* Updated `tokio-util` version to `^0.7` to allow for any compatible version within the minor version 7.
* Updated `tokio-stream` version to `^0.1` to allow for any compatible version within the minor version 1.
Closes #828
=> chore: relax the required version of tokio.

Cargo.lock, Cargo.toml
Removes the git dependencies for `eigensdk` and `eigenlayer-contract-deployer`.
The dynosaur git dependency (the only one remaining) is removed in #834
=> fix: remove eigenlayer git dependencies

.github/workflows/ci.yml, crates/macros/src/lib.rs
Since we use on some nightly options. They get ignored in CI currently.
=> chore(ci): use nightly rustfmt

Cargo.lock, Cargo.toml, crates/keystore/Cargo.toml, crates/keystore/src/error.rs, crates/keystore/src/storage/mod.rs, crates/keystore/src/storage/substrate.rs
This pull request introduces a new Substrate-backed keystore implementation in the `keystore` crate. The changes include adding new dependencies, updating the error handling, and implementing the Substrate storage module.
* Added `sp-keystore`, `sc-keystore`, `sp-application-crypto`, `scale-info`, and `parity-scale-codec` dependencies to `Cargo.toml` files. [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R128-R132) [[2]](diffhunk://#diff-7bff47a0c4db54bd3e8805cca7df05e2806c3ce95877b46fb23dec51b91a9e7aR66-R72)
* Added new error variants `KeystoreOperationNotSupported` and `SpKeystoreError` to the `Error` enum in `crates/keystore/src/error.rs`. [[1]](diffhunk://#diff-ccc71ec1242979c3b8ce804075c48d56ed1b8b0891c754bae186b611219fe986R29-R31) …
=> feat: add support for substrate keystore backend.

Cargo.toml, crates/keystore/src/keystore/config.rs, crates/keystore/src/keystore/mod.rs, crates/keystore/src/storage/mod.rs, crates/keystore/src/storage/substrate.rs, crates/networking/extensions/agg-sig-gossip/src/aggregator_selection.rs, rust-toolchain.toml
These are missed commits from #838 
---
This pull request includes several updates to the `keystore` module, as well as a version bump for the Rust toolchain. The most important changes involve adding support for Substrate keystore storage and updating the Rust version.
* Added support for Substrate keystore storage by introducing the `SubstrateStorage` struct and implementing necessary traits such as `Debug` and `Clone`. [[1]](diffhunk://#diff-31de59bda2bc18a1f2975b0c8e438830a1fe829bca0dc0d8aa961f809e58625dR45-R67) [[2]](diffhunk://#diff-315637bc7f6857287803b2efba5b300bfb22156c0767d483c1ad8aed90bad68fR1-R30) [[3]](diffhunk://#diff-315637bc7f6857287803b2efba5b300bfb22156c0767d483c1ad8aed90bad68fR60-R74)
* Implemented a new method `substrate` in `KeystoreConfig` to register a Substrate …
=> chore: add docs for the new substrate based keystore backend

Cargo.lock, examples/incredible-squaring/Cargo.lock
`crossbeam-channel` 0.5.14 was yanked. Need to bump it to publish.
=> chore: cargo update

.github/workflows/ci.yml, crates/sdk/Cargo.toml
The docs were being built with `all-features` before, which meant both `std` and `web` were enabled, which isn't valid.
=> fix: only build docs with `std` feature

cli/src/command/run/tangle.rs, crates/clients/tangle/src/client.rs, crates/manager/src/executor/mod.rs
These are cherrypicked commits from https://github.com/tangle-network/blueprint/compare/main...polkadot-stable2407 that I want to upstream them.
---
This pull request introduces improvements to the `TangleClient` and `BlueprintManager` components, focusing on better modularity, enhanced error handling, and code clarity. The most significant changes include refactoring the `TangleClient` initialization process, introducing a new function for running the `BlueprintManager` with a keystore, and improving error handling in the `handle_init` function.
* Refactored the `TangleClient::new` method to delegate initialization to a new `TangleClient::with_keystore` method, allowing the client to be created with an existing `Keystore`. This improves flexibility and modularity.
* Updated the …
=> feat: allow for blueprint manage to take a keystore.

crates/core/src/extract/job_id.rs, crates/core/src/job_call/job_id.rs, crates/core/src/job_call/mod.rs, crates/core/src/lib.rs, crates/producers-extra/src/cron.rs, crates/router/src/job_id_router.rs, crates/router/src/lib.rs, crates/router/src/routing.rs
The trait was unnecessary, just use `Into<JobId>`.
=> refactor(core)!: remove `IntoJobId` trait

release-plz.toml
Right now the release CI is super slow and usually requires multiple runs since it runs out of disk space.
Verification isn't necessary since CI already verifies that the crates build.
=> chore(ci): add `--no-verify` on publish

cli/src/command/create/types.rs
`cargo tangle blueprint create` was always defaulting to `--eigenlayer bls`, even if you passed `--tangle`
=> fix(cli): stop always choosing eigenlayer bls template

Cargo.lock, crates/networking/Cargo.toml, crates/networking/extensions/round-based/src/lib.rs, crates/networking/extensions/round-based/tests/rand_protocol.rs, crates/networking/src/behaviours.rs, crates/networking/src/blueprint_protocol/behaviour.rs, crates/networking/src/blueprint_protocol/handler.rs, crates/networking/src/discovery/behaviour.rs, crates/networking/src/discovery/config.rs, crates/networking/src/discovery/peers.rs, crates/networking/src/service.rs, crates/networking/src/service_handle.rs, crates/networking/src/test_utils/mod.rs, crates/networking/src/tests/blueprint_protocol.rs, crates/networking/src/tests/discovery.rs, crates/networking/src/tests/gossip.rs, crates/networking/src/tests/handshake.rs
Replaces tracing log macros with those in `blueprint-core`
=> fix(blueprint-networking): use blueprint-core log macros

.github/workflows/ci.yml
Removes the redundant installation of protoc in CI. Also will solve rate limit issue causing certain checks to fail randomly.
=> fix(ci): redundant protoc install

Cargo.lock, Cargo.toml, crates/auth/src/proxy.rs, crates/manager/Cargo.toml, crates/manager/src/config.rs, crates/manager/src/error.rs, crates/manager/src/executor/mod.rs
This pull request introduces a new authentication proxy feature to the Blueprint Manager, along with associated configuration, routing, and error handling changes. The most significant updates include adding the `blueprint-auth` crate, implementing the authentication proxy server, and updating the routing structure for API endpoints.
* Added the `blueprint-auth` crate dependency to both `Cargo.toml` files (`Cargo.toml` and `crates/manager/Cargo.toml`) to enable authentication proxy functionality. [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R67) [[2]](diffhunk://#diff-aca567fc21e8562c528fb2590c52ee12e11310aeb91a83964c3d7fa96e100cceR27-R29)
* Introduced the `AuthProxyOpts` struct in `crates/manager/src/config.rs` to configure the authentication …
=> feat: add auth proxy to blueprint manager

cli/src/command/create/mod.rs, cli/src/main.rs, crates/macros/src/lib.rs, crates/manager/Cargo.toml
Allows `cargo-tangle blueprint create` to be run without requiring interaction. 
The following flags/functionalities were added:
- `--define`: Allows users to define individual variables for the templates i.e., `--define gh-username=myname`. Any missing values from our templates are automatically passed with their default value (or an empty string for string values)
- `--template_values_file`: Allows a user to specify a file with `key=value` pairs that define template variables. Using this will result in cargo-generate running in silent mode, so it will fail if there are missing values. This is required so that it doesn't hang while waiting for user input if it were automated
- `--skip-prompts`: Removes the interactive part of the command, making it possible to run when user input is not …
=> feat(cli): blueprint create without interaction

release-plz.toml
This is needed since the release workflow now takes ~90min, which goes outside the generated token's lifetime
=> chore(ci): temporarily disable semver checks for release-plz

.github/workflows/ci.yml
Getting to the point where jobs are failing due to disk space
=> chore(ci): add free disk space action to clippy/tests

crates/chain-setup/tangle/src/deploy.rs
This pull request includes a small but important change to the `deploy_contracts_to_tangle` function in `crates/chain-setup/tangle/src/deploy.rs`. The change expands the validation of the `rpc_url` to allow both `ws://` and `wss://` protocols, improving compatibility with secure WebSocket connections.
=> fix: assert the rpc url starts with `ws` not `ws:` to support `wss` too

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/src/lib.rs, cli/src/main.rs
This pull request introduces support for `rustls` as a TLS library in the project, along with necessary configuration and setup changes. The most important updates include adding `rustls` dependencies, implementing a function to install the default crypto provider, and ensuring the crypto provider is initialized in the main function.
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R228): Added `rustls` as a dependency with version `0.23` and disabled default features. This enables TLS functionality using `rustls`.
* [`cli/Cargo.toml`](diffhunk://#diff-6057d83fb675b27e99f187fa354690b6597018c390cbd50eac854a56233d2addR53): Added `rustls` to the workspace dependencies for the CLI module.
* …
=> feat: add rustls as default crypto provider

Cargo.lock, Cargo.toml, crates/chain-setup/tangle/src/deploy.rs, crates/chain-setup/tangle/src/lib.rs, crates/chain-setup/tangle/src/transactions.rs
This pull request simplifies the handling of blueprint-related data in the `chain-setup/tangle` crate by replacing multiple individual types with a single `Blueprint` type. Additionally, it updates the `tangle-subxt` dependency to its latest version. Below are the most important changes grouped by theme:
* Updated the `tangle-subxt` dependency from version `0.18.0` to `0.19.0` in `Cargo.toml` to incorporate the latest features and improvements.
* Consolidated multiple individual types (`Metadata`, `Typedef`, `MembershipModel`, `SecurityRequirements`, and `PriceTargets`) into a single `Blueprint` type in the `generate_service_blueprint` function. This change simplifies the function's return type and internal logic. [[1]](diffhunk://#diff-b130117359ed17d3e8958fba1b9494995b057fc4b7578d50fd72a …
=> chore: update tangle-subxt dependency to v0.19

Cargo.lock, crates/qos/Cargo.toml, examples/incredible-squaring/Cargo.lock
also fix the `blueprint-*` dev dependencies that were keeping it from being published.
=> chore(qos): cleanup dependencies

Cargo.lock, Cargo.toml, crates/chain-setup/tangle/src/lib.rs
This pull request updates dependencies and constants to align with the latest versions of the Tangle network. The changes ensure compatibility with the updated Tangle testnet runtime and binaries.
* Updated the `tangle-subxt` dependency from version `0.19.0` to `0.20.0` in `Cargo.toml` to use the latest features and fixes.
* Updated the Tangle release URLs in `crates/chain-setup/tangle/src/lib.rs` to point to version `1.3.9` binaries for both macOS and Linux platforms, replacing the previous `1.3.8` version.
=> chore: update tangle-subxt to v0.20.0

crates/auth/Cargo.toml, crates/auth/src/main.rs, crates/pricing-engine/Cargo.toml, flake.lock
This pull request adds an easy way to run the auth proxy locally for testing and it can be ran using the following command:
```
cargo run -p blueprint-auth --features standalone
```
---
This pull request introduces a new standalone binary for the `auth-server` in the `crates/auth` crate, along with updates to dependencies and features to support its functionality. The key changes include defining the binary, adding necessary dependencies, and implementing the main entry point for the server.
* **Binary Definition**: Added a new standalone binary named `auth-server` in `crates/auth/Cargo.toml`. It requires the `standalone` feature and specifies `src/main.rs` as its entry point.
* **Main Entry Point**: Implemented the `main` function in `crates/auth/src/main.rs`, which initializes a …
=> feat: standalone auth proxy

Cargo.lock, Cargo.toml, crates/chain-setup/tangle/src/lib.rs, crates/runner/src/lib.rs, rust-toolchain.toml
* update `tangle-subxt` to 0.23.0
* update tangle binary to 1.4.2
* bump rust-version to 1.88
* fix `clippy::io_other_error`
=> chore!: dependency updates
